### ISSUE TITLE
test for pubsub store drop connections

### ISSUE THREAD

**Issue by lsbardel** [quantmind/pulsar-queue#2]
Tasks are retrieved from a distributed task queue which is associated with a connection with the queue broker (redis).
What happens if the connection is dropped?
What should the consumer do?

**Comment by acmk01** [comment]
There should be a mechanism of confirmation on both sides. Consumer should know that broker confirmed state of tasks and same knowledge should be on broker's side.

With that in mind my view on the options for the unconfirmed tasks is:
- try to restore connection and make sure the sate is consistent
     * broker confirms tasks state, 
     *or if not, make sure other consumers are not engaged with the tasks (we may call it 'collision') and update broker, 
     *or if other consumers engaged with the tasks, use some logic on how to sort the situation (collision handler)
- cancel
- complete

These options may go to config as ways of behavior or linked to task types
