### ISSUE TITLE
Not possible to queue a task from a CPUBOUND task

### ISSUE THREAD

**Issue by pvanderlinden** [quantmind/pulsar-queue#9]
If you queue a task at the end of a CPUBOUND task, the task never get's queued.
A possibility is to wait for it, but that means the CPUBOUND task is not finished till the queued task is finished too.

**Comment by lsbardel** [comment]
You can now ``wait(queue_task(name, callback=False))``.
This guaranties the task is queued but does not wait for its execution.

**Comment by pvanderlinden** [comment]
Thanks
